### ISSUE TITLE
Day 02 assignment

### ISSUE THREAD

**Issue by AlonGersh** [CatalinaDonic/CatalinaDonic.github.io#2]
Hi Catalina,

I'm reaching out as part of Day 02 assignment. I really liked the lab's logo! 
I have a small suggestion: you might consider adding a brief description of your research focus or your lab’s main research area. Alternatively, you could include a link to your lab’s website.

Good luck with your PhD and the course :)

**Comment by AlonGersh** [comment]
@liroh99

**Comment by CatalinaDonic** [comment]
Hi Alon,

Thank you for your comment! I updated the page to include a link to my lab's website and also elaborated a bit about my research.

Good luck with your PhD and the course as well! :)
Catalina
